typography_spectrum: 0.7562202527187765
color:
  brandStrength: 0.5623185627628118
  lightness: 0.7816491548437625
  saturation: 0.2452174441423267
  rhythmicContrast: 0.3286425967235118
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.3276179328095168
author:
  name: Philip J Owen
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/47c5ded8-3a35-46e0-98d1-ec702705678c.png
name: mysticky
navigation:
  - name: 'Friends Group Income Protection '
    id: 17fafd8e-e807-4bb8-a1e4-4ee6d00e9e17
    type: content
  - name: About us
    id: 1d13c25c-1e47-4dc0-8aef-493b7b1d60ce
    type: content
title: Creative & Design for Business
description: Design & Digital for Business
